docker:
  image: yegor256/rultor-image:1.15.0
install: |-
  sudo gem install texsc:0.6.0
  sudo gem install texqc:0.6.0
  sudo tlmgr option repository ctan
  sudo tlmgr --verify-repo=none update --self
  sudo tlmgr --verify-repo=none update l3build docshots iexec
merge:
  script: |-
    l3build ctan --show-log-on-error
release:
  script: |-
    l3build tag ${tag}
    l3build ctan --show-log-on-error
    texsc
    texqc
    git commit -am "version set to ${tag}"
    echo 'y' | l3build upload --halt-on-error
