# SPDX-FileCopyrightText: Copyright (c) 2022-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/latex
install: |-
  sudo update-depends.sh
merge:
  script: |-
    l3build ctan --show-log-on-error
release:
  pre: false
  script: |-
    l3build tag ${tag}
    l3build ctan --show-log-on-error
    texsc
    texqc
    git commit -am "version set to ${tag}"
    echo 'y' | l3build upload --halt-on-error
